spring:
  application:
    name: eureka-server-clustered

server:
  port: ${discovery.port}

eureka:
  instance:
    hostname: ${discovery.host}
  client:
    register-with-eureka: true
    fetch-registry: true   
    serviceUrl:
      defaultZone: ${discovery.defaultZone}     