version: "2"
services:
 mysql:
  image: "mysql"
  hostname: mysql   
  expose:
   - "3306"
  ports:
   - "23306:3306"
 discovery1:
  image: "qf-discovery-facade:0.0.1-SNAPSHOT"
  networks: 
   - eureka-net
  hostname: discovery1
  ports:
   - "9761:9761"
  environment:
     discovery.host: discovery1
     discovery.port: 9761
     discovery.defaultZone: http://discovery2:9762/eureka/,http://discovery3:9763/eureka/

 discovery2:
  image: "qf-discovery-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net
  hostname: discovery2
  ports:
   - "9762:9762"
  environment:
     discovery.host: discovery2
     discovery.port: 9762
     discovery.defaultZone: http://discovery1:9761/eureka/,http://discovery3:9763/eureka/

 discovery3:
  image: "qf-discovery-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net
  hostname: discovery3
  ports:
   - "9763:9763"
  environment:
     discovery.host: discovery3
     discovery.port: 9763
     discovery.defaultZone: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/

 config1:
  image: "qf-config-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net  
  hostname: config1
  depends_on: 
   - discovery1
   - discovery2
   - discovery3   
  environment:
     config.port: 9888
     config.application.name: config
     config.git.uri: https://github.com/lcgustc/qf-config/
     config.git.username: liuchaogan@163.com
     config.git.password: 6515579lcg308
     config.env: docker
     config.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
  ports:
    - "9888:9888"

 config2:
  image: "qf-config-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net  
  hostname: config2    
  depends_on: 
   - discovery1
   - discovery2
   - discovery3 
  environment:
     config.port: 9889
     config.application.name: config
     config.git.uri: https://github.com/lcgustc/qf-config/
     config.git.username: liuchaogan@163.com
     config.git.password: 6515579lcg308
     config.env: docker
     config.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
  ports:
    - "9889:9889"
    
 person1:
  image: "qf-person-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: person1
  volumes:
   - /home/logs/logback/person1:/home/logs/logback/qf-person
  privileged: true   
  depends_on: 
   - discovery1
   - discovery2
   - discovery3 
   - mysql
   - config1
   - config2   
  environment:
     person.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     person.config.profile: docker
     mysql: mysql
     person.port: 9082
  ports:
    - "9082:9082"

 person2:
  image: "qf-person-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: person2
  volumes:
   - /home/logs/logback/person2:/home/logs/logback/qf-person
  privileged: true   
  depends_on: 
   - discovery1
   - discovery2
   - discovery3 
   - mysql
   - config1
   - config2  
  environment:
     person.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     person.config.profile: docker
     mysql: mysql
     person.port: 9083
  ports:
    - "9083:9083"    

     
networks:
  eureka-net:
    driver: bridge
