version: "2"
services:
 person1:
  image: "qf-person-facade:0.0.1-SNAPSHOT"
  hostname: person1
  volumes:
   - /home/logs/logback/person1:/home/logs/logback/qf-person
  privileged: true  
  external_links:
    - DiscoveryStack/discovery1:discovery1
    - DiscoveryStack/discovery2:discovery2
    - ConfigStack/config1:config1
    - ConfigStack/config2:config2
    - MySQLStack/mysql:mysql
    - RabbitMQStack/rabbitmq :rabbitmq
  environment:
     person.eureka.cluster: http://discovery1.DiscoveryStack:9761/eureka/,http://discovery2.DiscoveryStack:9762/eureka/
     person.config.profile: docker
     mysql: mysql.MySQLStack
     person.port: 9082
     sleuth.rabbitmq.host: rabbitmq.RabbitMQStack
     sleuth.rabbitmq.port: 5672
     sleuth.rabbitmq.username: guest
     sleuth.rabbitmq.password: guest
     sleuth.rabbitmq.virtualHost: /     
  ports:
    - "9082:9082"

 person2:
  image: "qf-person-facade:0.0.1-SNAPSHOT"
  hostname: person2
  volumes:
   - /home/logs/logback/person2:/home/logs/logback/qf-person
  privileged: true    
  external_links:
    - DiscoveryStack/discovery1:discovery1
    - DiscoveryStack/discovery2:discovery2
    - ConfigStack/config1:config1
    - ConfigStack/config2:config2
    - MySQLStack/mysql:mysql
    - RabbitMQStack/rabbitmq :rabbitmq
  environment:
     person.eureka.cluster: http://discovery1.DiscoveryStack:9761/eureka/,http://discovery2.DiscoveryStack:9762/eureka/
     person.config.profile: docker
     mysql: mysql.MySQLStack
     person.port: 9083
     sleuth.rabbitmq.host: rabbitmq.RabbitMQStack
     sleuth.rabbitmq.port: 5672
     sleuth.rabbitmq.username: guest
     sleuth.rabbitmq.password: guest
     sleuth.rabbitmq.virtualHost: /     
  ports:
    - "9083:9083"