version: "2"
services:
 mysql:
  image: "mysql"
  hostname: mysql
  networks: 
   - eureka-net  
  expose:
   - "3306"
  ports:
   - "23306:3306"  

 rabbitmq:
  image: bijukunjummen/rabbitmq-server
  hostname: rabbitmq
  networks: 
   - eureka-net  
  ports:
    - "5673:5672"
    - "4370:4369"
    - "1884:1883"
    - "15673:15672"
    - "25673:25672"
  environment:
    - RABBITMQ_DEFAULT_USER=myuser
    - RABBITMQ_DEFAULT_PASS=mypass    
   
 discovery1:
  image: "qf-discovery-facade:0.0.1-SNAPSHOT"
  networks: 
   - eureka-net
  hostname: discovery1
  ports:
   - "9761:9761"
  environment:
     discovery.host: discovery1
     discovery.port: 9761
     discovery.defaultZone: http://discovery2:9762/eureka/,http://discovery3:9763/eureka/

 discovery2:
  image: "qf-discovery-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net
  hostname: discovery2
  ports:
   - "9762:9762"
  environment:
     discovery.host: discovery2
     discovery.port: 9762
     discovery.defaultZone: http://discovery1:9761/eureka/,http://discovery3:9763/eureka/

 discovery3:
  image: "qf-discovery-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net
  hostname: discovery3
  ports:
   - "9763:9763"
  environment:
     discovery.host: discovery3
     discovery.port: 9763
     discovery.defaultZone: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/

 config1:
  image: "qf-config-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net  
  hostname: config1
  depends_on: 
   - discovery1
   - discovery2
   - discovery3   
  environment:
     config.port: 9888
     config.application.name: config
     config.git.uri: https://github.com/lcgustc/qf-config/
     config.git.username: liuchaogan@163.com
     config.git.password: 6515579lcg308
     config.env: docker
     config.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
  ports:
    - "9888:9888"

 config2:
  image: "qf-config-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net  
  hostname: config2    
  depends_on: 
   - discovery1
   - discovery2
   - discovery3 
  environment:
     config.port: 9889
     config.application.name: config
     config.git.uri: https://github.com/lcgustc/qf-config/
     config.git.username: liuchaogan@163.com
     config.git.password: 6515579lcg308
     config.env: docker
     config.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
  ports:
    - "9889:9889"
    
 person1:
  image: "qf-person-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: person1
  volumes:
   - /home/logs/logback/person1:/home/logs/logback/qf-person
  privileged: true   
  depends_on: 
   - discovery1
   - discovery2
   - discovery3 
   - mysql
   - config1
   - config2   
  environment:
     person.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     person.config.profile: docker
     mysql: mysql
     person.port: 9082
     sleuth.rabbitmq.host: rabbitmq
     sleuth.rabbitmq.port: 5672
     sleuth.rabbitmq.username: myuser
     sleuth.rabbitmq.password: mypass
     sleuth.rabbitmq.virtualHost: /     
  ports:
    - "9082:9082"

 person2:
  image: "qf-person-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: person2
  volumes:
   - /home/logs/logback/person2:/home/logs/logback/qf-person
  privileged: true   
  depends_on: 
   - discovery1
   - discovery2
   - discovery3 
   - mysql
   - config1
   - config2  
  environment:
     person.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     person.config.profile: docker
     mysql: mysql
     person.port: 9083
     sleuth.rabbitmq.host: rabbitmq
     sleuth.rabbitmq.port: 5672
     sleuth.rabbitmq.username: myuser
     sleuth.rabbitmq.password: mypass
     sleuth.rabbitmq.virtualHost: /     
  ports:
    - "9083:9083"    

 some1:
  image: "qf-some-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: some1
  volumes:
   - /home/logs/logback/some1:/home/logs/logback/qf-some
  privileged: true   
  depends_on: 
   - person1
   - person2
  environment:
     some.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     some.config.profile: docker
     some.port: 9084
     sleuth.rabbitmq.host: rabbitmq
     sleuth.rabbitmq.port: 5672
     sleuth.rabbitmq.username: myuser
     sleuth.rabbitmq.password: mypass
     sleuth.rabbitmq.virtualHost: /     
  ports:
    - "9084:9084"

 some2:
  image: "qf-some-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: some2
  volumes:
   - /home/logs/logback/some2:/home/logs/logback/qf-some
  privileged: true   
  depends_on: 
   - person1
   - person2
  environment:
     some.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     some.config.profile: docker
     some.port: 9085
     sleuth.rabbitmq.host: rabbitmq
     sleuth.rabbitmq.port: 5672
     sleuth.rabbitmq.username: myuser
     sleuth.rabbitmq.password: mypass
     sleuth.rabbitmq.virtualHost: /     
  ports:
    - "9085:9085"    

 gateway1:
  image: "qf-gateway-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: gateway1
  volumes:
   - /home/logs/logback/gateway1:/home/logs/logback/qf-gateway
  privileged: true   
  depends_on: 
   - some1
   - some2
  environment:
     gateway.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     gateway.port: 9086
     sleuth.rabbitmq.host: rabbitmq
     sleuth.rabbitmq.port: 5672
     sleuth.rabbitmq.username: myuser
     sleuth.rabbitmq.password: mypass
     sleuth.rabbitmq.virtualHost: /     
  ports:
    - "9086:9086"  
    
 gateway2:
  image: "qf-gateway-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: gateway2
  volumes:
   - /home/logs/logback/gateway2:/home/logs/logback/qf-gateway
  privileged: true   
  depends_on: 
   - some1
   - some2
  environment:
     gateway.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     gateway.port: 9087
     sleuth.rabbitmq.host: rabbitmq
     sleuth.rabbitmq.port: 5672
     sleuth.rabbitmq.username: myuser
     sleuth.rabbitmq.password: mypass
     sleuth.rabbitmq.virtualHost: /     
  ports:
    - "9087:9087"     

 turbine:
  image: "qf-turbine-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: turbine
  volumes:
   - /home/logs/logback/turbine:/home/logs/logback/qf-turbine
  privileged: true   
  depends_on: 
   - gateway1
   - gateway2
  environment:
     turbine.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     turbine.port: 9088
  ports:
    - "9088:9088"

 msadmin:
  image: "qf-msadmin-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: msadmin
  volumes:
   - /home/logs/logback/msadmin:/home/logs/logback/qf-msadmin
  privileged: true   
  depends_on: 
   - turbine
  environment:
     msadmin.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     msadmin.port: 9089
     msadmin.turbine.url: http://turbine:9088/turbine.stream
  ports:
    - "9089:9089"  

 sleuth:
  image: "qf-sleuth-facade:0.0.1-SNAPSHOT"
  networks:
   - eureka-net   
  hostname: sleuth
  volumes:
   - /home/logs/logback/sleuth:/home/logs/logback/qf-sleuth
  privileged: true   
  depends_on: 
   - gateway1
   - gateway2
   - rabbitmq
  environment:
     sleuth.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     sleuth.port: 9090
     sleuth.turbine.url: http://turbine:9088/turbine.stream
     sleuth.rabbitmq.host: rabbitmq
     sleuth.rabbitmq.port: 5672
     sleuth.rabbitmq.username: guest
     sleuth.rabbitmq.password: guest
     sleuth.rabbitmq.virtualHost: /
     sleuth.mysql.url: jdbc:mysql://mysql:3306/db_sleuth
     sleuth.mysql.username: root
     sleuth.mysql.passowrd: passowrd
  ports:
    - "9090:9090"    
    
    
networks:
  eureka-net:
    driver: bridge
