version: "2"
services:
 msadmin:
  image: "qf-msadmin-facade:0.0.1-SNAPSHOT"  
  hostname: msadmin
  volumes:
   - /home/logs/logback/msadmin:/home/logs/logback/qf-msadmin
  privileged: true   
  external_links:
    - DiscoveryStack/discovery1:discovery1
    - DiscoveryStack/discovery2:discovery2
    - ConfigStack/config1:config1
    - ConfigStack/config2:config2
    - PersonStack/person1:person1
    - PersonStack/person2:person2
    - SomeStack/some1:some1
    - SomeStack/some2:some2
    - GatewayStack/gateway1:gateway1 
    - GatewayStack/gateway2:gateway2
    - TurbineStack/turbine:turbine
    - SleuthStack/sleuth:sleuth
  environment:
     msadmin.eureka.cluster: http://discovery1:9761/eureka/,http://discovery2:9762/eureka/,http://discovery3:9763/eureka/
     msadmin.port: 9089
     msadmin.turbine.url: http://turbine:9088/turbine.stream
  ports:
    - "9089:9089" 